[pytest]
DJANGO_SETTINGS_MODULE = stitchflow.settings
pythonpath = src
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -p no:warnings --basetemp=C:\Users\hugob\AppData\Local\Temp\pytest-stichflow
