# Generated by Django 6.0.5 on 2026-06-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='conversion_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
