# Generated by Django 6.0.5 on 2026-06-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0002_conversionjob_conversion_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='target_width_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
