# Generated by Django 6.0.5 on 2026-06-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0003_conversionjob_target_width_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
