# Generated by Django 6.0.5 on 2026-06-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0004_conversionjob_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='n_colors',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='remove_background',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='vectorized_svg_file',
            field=models.FileField(blank=True, null=True, upload_to='conversions/vectorized/'),
        ),
    ]
