# Generated by Django 6.0.6 on 2026-06-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0005_conversionjob_n_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionjob',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('awaiting_svg_validation', 'Attente validation SVG'), ('completed', 'Terminé'), ('failed', 'Échoué')], db_index=True, default='pending', max_length=30),
        ),
    ]
