# Generated by Django 6.0.6 on 2026-07-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0007_add_user_to_conversion_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='progress_pct',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='progress_step',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
