# Generated by Django 6.0.6 on 2026-07-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0008_conversionjob_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='prepared_svg_file',
            field=models.FileField(blank=True, null=True, upload_to='conversions/prepared/'),
        ),
    ]
