# Generated by Django 6.0.6 on 2026-07-09 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0009_prepared_svg_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['-created_at'], name='conversions_created_1371cf_idx'),
        ),
    ]
