# Generated by Django 6.0.6 on 2026-07-03 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_model', models.CharField(choices=[('PR1050X', 'Brother PR1050X (10 aiguilles)'), ('PE800', 'Brother PE800'), ('SE700', 'Brother SE700'), ('MC500E', 'Janome MC500E'), ('CUSTOM', 'Personnalisé')], default='PR1050X', max_length=20, verbose_name='Modèle de machine')),
                ('machine_needles', models.PositiveSmallIntegerField(default=10, verbose_name="Nombre d'aiguilles")),
                ('machine_hoop_width_mm', models.PositiveSmallIntegerField(default=360, verbose_name='Largeur zone de broderie (mm)')),
                ('machine_hoop_height_mm', models.PositiveSmallIntegerField(default=200, verbose_name='Hauteur zone de broderie (mm)')),
                ('machine_format', models.CharField(choices=[('PES', 'PES (Brother)'), ('DST', 'DST (Tajima)'), ('JEF', 'JEF (Janome)'), ('VP3', 'VP3 (Husqvarna/Pfaff)')], default='PES', max_length=4, verbose_name='Format de fichier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
