# Generated by Django 6.0.5 on 2026-06-01 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='conversions/uploads/')),
                ('source_format', models.CharField(default='svg', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('output_file', models.FileField(blank=True, upload_to='conversions/outputs/')),
                ('preview_file', models.FileField(blank=True, null=True, upload_to='conversions/previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
